### ISSUE TITLE
I get "you earned 0xp for playing on the server"

### ISSUE THREAD

**Issue by dogdaycare** [chesiren/DarkRP-Leveling-System-2.7.0#3]
If i !setlevel to 2 for example and i !setlevel back to 0 i get the 100xp. What can i do to fix it?

**Comment by chesiren** [comment]
When i try the addon on my computer, everything seems to work fine ,

- have you any error in your server console?
- are you sure that you're using only lastest addon version and not the original leveling system?
- are you using the last version of darkrp?

**Comment by dogdaycare** [comment]
I get a lot of .ttf errors from the script but thats about it

**Comment by dogdaycare** [comment]
Is there anyway to easily uninstall the level system? I’m gonna try to download it again and maybe it’ll fix it

**Comment by chesiren** [comment]
> 
> 
> Is there anyway to easily uninstall the level system? I’m gonna try to download it again and maybe it’ll fix it

just delete the addon and remove it from your workshop collection and it will be removed from the server
